apiVersion: apps/v1
kind: Deployment
metadata:
 name: sample-python
 labels:
   app: sample-python
spec:
 selector:
  matchLabels:
   app: sample-python
 template:
  metadata:
   labels:
    app: sample-python
spec:
 containers:
 - image: <ip_address_of_the_machine>:5000/sample-python-flask:latest
   name: python-flask
   imagePullPolicy: Always
   ports:
     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: sample-python-svc
spec:
    ports:
    - name: “sample-python”
      targetPort: 80
      port: 80
      nodePort: 30275
      protocol: TCP
   selector:
      app: sample-python
   type: NodePort